<?php 

$title = 'Edit Client';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'crm',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('nom'));
 echo $this->formRow($form->get('prenom'));
 echo $this->formRow($form->get('email'));
 echo $this->formRow($form->get('societe'));
 echo $this->formRow($form->get('telephone'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();