<?php 

$title = 'Modifier client';
$this->headTitle($title);
?>


<div class="modal-dialog">
    <div class="modal-content">
    	<div class="modal-header">			
				<h4 class="modal-title">
					<center> <?php echo $this->escapeHtml($title); ?> </center>
				</h4>
			</div>
			<div class="modal-body">

				 <?php
					 $form = $this->form;
					 $form->setAttribute('action', $this->url(
					     'crm',
					     array(
					         'action' => 'edit',
					         'id'     => $this->id,
					     )
					 ));
					 $form->prepare();
					
					 echo $this->form()->openTag($form);
					 echo $this->formHidden($form->get('id'));
					 echo $this->formRow($form->get('nom'));?><br><br><?php
					 echo $this->formRow($form->get('prenom'));?><br><br><?php
					 echo $this->formRow($form->get('email'));?><br><br><?php
					 echo $this->formRow($form->get('societe'));?><br><br><?php
					 echo $this->formRow($form->get('telephone'));?><br><br><center><?php
					 echo $this->formSubmit($form->get('submit'));?></center><?php
					 echo $this->form()->closeTag();
				 ?>
				</div>
 		</div>
 	</div>
				 