<?php
$title = 'Liste des Clients';
 $this->headTitle($title);
 ?>
 
 <a style="float: right;" href="<?php echo $this->url('auth', array('action'=>'logOut'));?>" class="btn btn-primary" > 
 		<?php echo $this->translate('Deconexion'); ?><br>
 	</a>  
 <br><br><br><br>
 
 

 
 <div class="modal-dialog">
    <div class="modal-content">
    	<div class="modal-header">
    		<p>
     			<a href="<?php  echo $this->url('crm', array('action'=>'add'));?>" 
     				 type="button" 
     				 class="button"
     				 style="float: right;">
     				  +
     			</a>
 				</p>			
				<h4 class="modal-title">
					<center><?php echo $this->escapeHtml($title); ?></center>
				</h4>
			</div>
    	<div class="modal-body">
 				<table class="table">
 						<?php foreach ($clients as $client) : ?>
 					<tr>
     				<td>
     					<a href="<?php echo $this->url('crm', array('action'=>'afficheclient', 'id' => $client->id));?>">
     		 				<?php echo $this->escapeHtml($client->prenom);?> &nbsp;
     		 				<?php echo $this->escapeHtml($client->nom);?> 
      				</a>
     				</td>
 					</tr>
 					<?php endforeach; ?>
 				</table>
 			</div>
 		</div>
 	</div>