<?php
$title = 'Ajouter un Album';
$this->headTitle($title);
?>
<h1>
	<center>		<?php echo $this->escapeHtml($title); ?> </center>
</h1><br>
<?php
$form->setAttribute('action', $this->url('album', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));?><br><br><?php 
echo $this->formRow($form->get('artist'));?><br><br><?php
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
