<?php
$title = 'Modifier Music';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('album', array('action' => 'modifiermusic','id' => $this->id,)));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo '<br />';
echo $this->formRow($form->get('artist'));
echo '<br />';
echo $this->formRow($form->get('description'));
echo '<br />';
echo $this->formRow($form->get('image'));
echo '<br />';
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
<div style="margin-top:20px;">
 <?php // ici liste des photo
 
 foreach ($images as $image) : ?>
		<a href="" >X</a>
		<img src="/other/img/<?php echo $image->id_chanson.'-'.$image->id_img.'.JPG' ?>" height="200px" width="200px"/>
		
 <?php endforeach; ?>
</div>